### ISSUE TITLE
An error has occurred: [Errno 2] No such file or directory: 'Configs\\OnlyFans\\Config.json'

### ISSUE THREAD

**Issue by sammas72** [jordon31/OnlySnap#40]
What's the error? File exist in the folder, I didn't modified it

An error has occurred: [Errno 2] No such file or directory: 'Configs\\OnlyFans\\Config.json'
Traceback (most recent call last):
  File "c:\Users\s.amista\Documents\NZD_PY\OnlySnap-main\OnlySnap.py", line 938, in <module>
    media_downloaded = download_posts(photo_posts, False, pbar)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\s.amista\Documents\NZD_PY\OnlySnap-main\OnlySnap.py", line 536, in download_posts
    was_downloaded = future.result()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\s.amista\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s.amista\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\s.amista\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\s.amista\Documents\NZD_PY\OnlySnap-main\OnlySnap.py", line 435, in download_media
    folder_name = get_year_folder(timestamp, type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\s.amista\Documents\NZD_PY\OnlySnap-main\OnlySnap.py", line 363, in get_year_folder
    with open(config_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Configs\\OnlyFans\\Config.json'

**Comment by jordon31** [comment]
mmm wait next update
